# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c0468e3fcc5b10978da70ac61892b107b4b026c77f89e2f177064d631977428c662029b974041cf4fbdc9b306999937fa072397c2478e8eb1518e038e152a22

test:
  secret_key_base: d2ce9fd0cbaee420a7902930c067994573ad1faa25daf1993552c68630f4c49f6061de65c2d2af3a5a5f1387961b9b9bc4f02517a96ce74cfc0318b132a94378

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
